
server:
    port: 8091
    servlet:
      context-path: /train

spring:
  datasource:
    username: root
    password: user123456
    url: jdbc:mysql://127.0.0.1:3306/train_db?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name : com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none

mybatis:
      mapper-locations: classpath:mapperxml/*.xml
      type-aliases-package: com.train.model.entity

logging:
   level:
      root: debug

config:
    version: 1
    encrypt: false
    password: a123456789
    deviceType: HIKVISION
    host : 192.168.1.153
    appKey : 27857924
    appSecret : 7knNk0zjY08KNgZgGVTQ

