spring:
  datasource:
      username: sa
      password: U$er123456
      url:  jdbc:sqlserver://192.168.1.117:1433;databasename=api2019
      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
