package com.train.model.entity;

import java.util.Date;

public class RegisterLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_register_log.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_register_log.uid
     *
     * @mbggenerated
     */
    private Long uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_register_log.register_method
     *
     * @mbggenerated
     */
    private int register_method;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_register_log.register_time
     *
     * @mbggenerated
     */
    private Date register_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_register_log.register_ip
     *
     * @mbggenerated
     */
    private String register_ip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_register_log.register_client
     *
     * @mbggenerated
     */
    private String register_client;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_register_log.id
     *
     * @return the value of tb_register_log.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_register_log.id
     *
     * @param id the value for tb_register_log.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_register_log.uid
     *
     * @return the value of tb_register_log.uid
     *
     * @mbggenerated
     */
    public Long getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_register_log.uid
     *
     * @param uid the value for tb_register_log.uid
     *
     * @mbggenerated
     */
    public void setUid(Long uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_register_log.register_method
     *
     * @return the value of tb_register_log.register_method
     *
     * @mbggenerated
     */
    public int getRegister_method() {
        return register_method;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_register_log.register_method
     *
     * @param register_method the value for tb_register_log.register_method
     *
     * @mbggenerated
     */
    public void setRegister_method(int register_method) {
        this.register_method = register_method;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_register_log.register_time
     *
     * @return the value of tb_register_log.register_time
     *
     * @mbggenerated
     */
    public Date getRegister_time() {
        return register_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_register_log.register_time
     *
     * @param register_time the value for tb_register_log.register_time
     *
     * @mbggenerated
     */
    public void setRegister_time(Date register_time) {
        this.register_time = register_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_register_log.register_ip
     *
     * @return the value of tb_register_log.register_ip
     *
     * @mbggenerated
     */
    public String getRegister_ip() {
        return register_ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_register_log.register_ip
     *
     * @param register_ip the value for tb_register_log.register_ip
     *
     * @mbggenerated
     */
    public void setRegister_ip(String register_ip) {
        this.register_ip = register_ip == null ? null : register_ip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_register_log.register_client
     *
     * @return the value of tb_register_log.register_client
     *
     * @mbggenerated
     */
    public String getRegister_client() {
        return register_client;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_register_log.register_client
     *
     * @param register_client the value for tb_register_log.register_client
     *
     * @mbggenerated
     */
    public void setRegister_client(String register_client) {
        this.register_client = register_client == null ? null : register_client.trim();
    }
}