package com.train.model.mapper;

import com.train.model.entity.RegisterLog;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Repository;

@Mapper
@Repository
public interface RegisterLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_register_log
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_register_log
     *
     * @mbggenerated
     */
    int insert(RegisterLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_register_log
     *
     * @mbggenerated
     */
    int insertSelective(RegisterLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_register_log
     *
     * @mbggenerated
     */
    RegisterLog selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_register_log
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(RegisterLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_register_log
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(RegisterLog record);
}